import React from 'react';
import { Navbar } from '@/components/Navbar';
import { motion } from 'framer-motion';

const LofiTermsOfService: React.FC = () => {
    return (
        <div className="w-full min-h-screen relative bg-zinc-50 dark:bg-zinc-950">
            {/* Simple gradient background for responsiveness and crawler-friendliness */}
            <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 via-transparent to-purple-500/5 pointer-events-none" />

            <div className="w-full min-h-screen flex flex-col relative z-10">
                <div className="w-full border-b border-purple-500/20 dark:border-purple-500/40 backdrop-blur-md bg-white/40 dark:bg-black/40">
                    <div className="px-4 md:px-6 py-4">
                        <Navbar />
                    </div>
                </div>
                <div className="flex-1 flex flex-col items-center py-12 px-4 md:px-6">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="w-full max-w-4xl bg-white/40 dark:bg-black/40 backdrop-blur-xl border border-purple-500/20 dark:border-purple-500/30 rounded-2xl p-8 md:p-12 shadow-2xl"
                    >
                        <div className="flex justify-start mb-8">
                            <a
                                href="/projects/lofi-station"
                                className="flex items-center gap-2 text-zinc-600 dark:text-zinc-400 hover:text-purple-500 transition-colors group"
                            >
                                <svg className="w-5 h-5 transform group-hover:-translate-x-1 transition-transform" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                                </svg>
                                Back to Lofi Station
                            </a>
                        </div>
                        <h1 className="text-4xl font-bold mb-8 text-zinc-900 dark:text-white text-center">Terms of Service for Lofi Station</h1>

                        <div className="space-y-6 text-zinc-700 dark:text-zinc-300 leading-relaxed text-sm md:text-base">
                            <section>
                                <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-3">1. Acceptance of Terms</h2>
                                <p>
                                    By accessing and using the Lofi Station, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-3">2. Description of Service</h2>
                                <p>
                                    The Lofi Station is an experimental tool for generating ambient lofi music using rule-based synthesis. It is provided "as-is" for personal, non-commercial use.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-3">3. Usage Rights & Licensing</h2>
                                <p>
                                    The music tracks generated by this platform are synthesized in real-time using rule-based algorithms.
                                </p>
                                <p className="mt-2 font-medium text-purple-600 dark:text-purple-400 font-mono">
                                    All tracks generated and downloaded from the Lofi Station are released under the MIT License.
                                </p>
                                <p className="mt-2 text-zinc-700 dark:text-zinc-300">
                                    This means you are free to use, copy, modify, merge, publish, or distribute the generated audio for any purpose, commercial or non-commercial, provided you include the original copyright notice where applicable.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-3">4. Limitation of Liability</h2>
                                <p>
                                    In no event shall the author be liable for any damages arising out of the use or inability to use the Lofi Station. We do not guarantee 100% uptime or the persistent availability of generated files.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-xl font-semibold text-zinc-900 dark:text-white mb-3">5. Termination</h2>
                                <p>
                                    We reserve the right to suspend or terminate your access to the Lofi Station at any time, without notice, for any violation of these terms or misuse of the platform.
                                </p>
                            </section>
                        </div>
                    </motion.div>
                </div>
            </div>
        </div>
    );
};

export default LofiTermsOfService;
